name: Clojure CI

on:
  push:
    branches:
    - '*'
  workflow_dispatch:
    inputs:
      mydata:
        description: 'enter data'
        type: string
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Run tests
      run: echo  sushil ${{ github.event.inputs.mydata }}
