name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    if: ${{ github.base_ref != 'master' }} 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0
          ref: sk
    - name: Build with Gradle
      run: ls -lrt
