name: Print Labels from Push Event

on:
  push:
    branches: []
jobs:
  print_labels:
    name: Print Labels Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Pull Request URL
        id: pr_url
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}"
          

      - name: Get Pull Request Number
        id: pr_number
        run: |
          pr_url="${{ steps.pr_url.outputs.url }}"
          pr_number=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "$pr_url" | jq -r '.url' | awk -F'/' '{print $NF}')
          echo "::set-output name=number::$pr_number"

      - name: Get Pull Request Labels
        id: pr_labels
        run: |
          pr_number="${{ steps.pr_number.outputs.number }}"
          labels=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${pr_number}/labels" \
            | jq -r '.[].name')
          echo "::set-output name=labels::$labels"

      - name: Print Labels
        run: |
          labels="${{ steps.pr_labels.outputs.labels }}"
          echo "Labels: $labels"
