name: Deploy
on:
  workflow_dispatch: {}
  push:

jobs:
  
  master-reset:
    name: Run Deploy Script with master
    runs-on: ubuntu-latest  
    steps:
      - name: Run

        run: |
          echo hello
          gh_ref='${{ github.ref_name }}'
          echo $gh_ref
