name: Deploy
on:
  schedule: # Run this job at 12AM GMT and 12PM GMT daily.
    - cron: '0 */12 * * *'
  workflow_dispatch: {}
  push:

jobs:
  deploy:
    name: Run Deploy Script
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: |
          exit 1


  master-reset:
    name: Run Deploy Script with master
    needs: 
      [
        deploy,
      ]
    if: failure()
    runs-on: ubuntu-latest
     
    steps:
      - name: Run

        run: |
          echo hello
