name: Print Labels from Push Event

on:
  workflow_dispatch: {}
  push:
    branches: []
jobs:
  check_pr_labels_job:
    runs-on: ubuntu-latest
    name: A job to check the PR labels contain given labels
    steps:
    - name: See result
      run: |
          tmp_filename="datadog-forwarder.zip.tmp-${uuid()}"
          curl -f -o $tmp_filename -L https://github.com/DataDog/datadog-serverless-functions/releases/download/aws-dd-forwarder-3.32.0/aws-dd-forwarder-3.32.0.zip"
          mv $tmp_filename datadog-forwarder.zip
    
