name: Prechecks

on:
  workflow_dispatch: {}
  push:
    branches-ignore:
      - bors/*.tmp
jobs:
  env:
    name: Env
    runs-on: ubuntu-latest
    steps:
      - name: Precheck
        run: |
          echo "Job ID: $GITHUB_JOB"
          echo "Run ID: $GITHUB_RUN_ID"
