name: Deploy
on:
  workflow_dispatch: {}
  push:
    branches-ignore:
      - master # Deploys happen before merge with bors.

jobs:
  last-job-status:
    name: Check last job status
    runs-on: ubuntu-latest
    steps:
      - name: last deploy job status
        run: |
          gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/sk-iiitg/hello-world/actions/runs
