name: Deploy
on:
  workflow_dispatch: {}
  workflow_call: {}
  push:
    branches-ignore:
      - master # Deploys happen before merge with bors.
  merge_group:
jobs:
  RETRY:
    name: retry job with
    runs-on: ubuntu-latest
    steps:
      - name: Kar lo retry
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 120
          max_attempts: 2
          retry_on: error
          command: |
            echo "hello"
            echo $github.event.pull_request.labels.*.name
  Revert:
    name: revert with master
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, 'no_revert')
    steps:
      - name: Kar lo retry
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 120
          max_attempts: 2
          retry_on: error
          command: |
            echo "hello yaar"         
  
