name: Deploy
on:
  workflow_dispatch: {}
  push:
    branches-ignore:
      - master # Deploys happen before merge with bors.

jobs:
  last-job-status:
    name: Check last job status
    runs-on: ubuntu-latest
    steps:
      - name: last deploy job status
        run: |
          response=$(curl -s -w "%{http_code}" \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          'https://api.github.com/repos/sk-iiitg/hello-world/actions/workflows/11665892/runs?per_page=100')
          http_code=$(tail -n1 <<< "$response")  # get the last line
          content=$(sed '$ d' <<< "$response")
          echo $http_code
          echo $content
