name: Deploy
on:
  workflow_dispatch: {}
  workflow_call: {}
  push:
    branches-ignore:
      - master # Deploys happen before merge with bors.
  merge_group:
jobs:
  RETRY:
    name: retry job with
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Kar lo retry
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 120
          max_attempts: 2
          retry_on: error
          command: |
            echo "hello"
            echo $github.event.pull_request.labels.*.name
            labels=$(echo "${{ github.event.pull_request.labels }}" | jq '.[].name')
            echo "Labels: $labels"
      - name: Get Pull Request Number
        id: pr_number
        run: |
          pr_number=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}" \
            | jq -r '.pull_request.url' | awk -F'/' '{print $NF}')
          echo "::set-output name=number::$pr_number"

      - name: Get Pull Request Labels
        id: pr_labels
        run: |
          pr_number="${{ steps.pr_number.outputs.number }}"
          labels=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${pr_number}/labels" \
            | jq -r '.[].name')
          echo "::set-output name=labels::$labels"

      - name: Print Labels
        run: |
          labels="${{ steps.pr_labels.outputs.labels }}"
          echo "Labels: $labels"      
            
  Revert:
    name: revert with master
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, 'no_revert')
    steps:
      - name: Kar lo retry
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 120
          max_attempts: 2
          retry_on: error
          command: |
            echo "hello yaar"         
  
