name: Deploy
on:
  workflow_dispatch: {}
  push:
    branches-ignore:
      - master # Deploys happen before merge with bors.

jobs:
  last-job-status:
    if: github.ref_name == 'bors/staging'|| action == 'workflow_dispatch'
    name: Check last job status
    runs-on: ubuntu-latest
    steps:
      - name: last deploy job status
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo hello
