name: Deploy

on:
  schedule:
    - cron: '27 11 * * 1-5'
  workflow_dispatch: {}
  push:
    branches-ignore:
      - bors/*.tmp
      - master # Deploys happen before merge with bors.
jobs:
  env:
    name: Env
    runs-on: ubuntu-latest
    steps:
      - name: Run
        id: run
        run: |
          ./deploy.sh \
            --dry-run=${{ needs.env.outputs.apply != 'true' }} \
            --safe=${{ vars.SAFE != 'false' }} \
            ${{ github.event_name != 'workflow_dispatch'  && github.event_name != 'schedule' && '--base-commit=origin/master' || '' }} \
            ci
