name: Integration Test - AUTO
on:
  workflow_dispatch:
    inputs:
      batch:
        description: 'Run at batch priority.'
        required: false
        type: boolean
        default: true
jobs:
  env:
    name: Env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  approval: # fails when timed out or denied.
    name: Require approvals
    needs:
      - env
    runs-on: ubuntu-latest
    steps:
      - name: Generate token 
        uses: actions/checkout@v3
      - name: sk
        run: sleep 30;
  run: # fails when timed out or denied.
    name: RUN JOB
    needs:
      - env
      - approval
    if: ${{ needs.approval.result == 'success' || needs.approval.result == null }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate token 
        uses: actions/checkout@v3     
        
        
